# Generated by Django 5.2.8 on 2025-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.JSONField()),
                ('range', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'airplanes_data',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.JSONField()),
                ('city', models.JSONField()),
                ('country', models.JSONField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timezone', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'airports_data',
            },
        ),
    ]
