# Generated by Django 5.2.8 on 2025-11-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('fare_conditions', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=20)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.airplane')),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('airplane', 'seat_no')},
            },
        ),
    ]
