# Generated by Django 5.2.8 on 2025-11-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0002_alter_airplane_airplane_code_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='airplane',
            field=models.ForeignKey(db_column='airplane_code', on_delete=django.db.models.deletion.CASCADE, to='airline_app.airplane'),
        ),
    ]
