# Generated by Django 5.2.8 on 2025-11-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0003_alter_seat_airplane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.airplane'),
        ),
    ]
