# Generated by Django 5.2.8 on 2025-11-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=64)),
                ('passenger_name', models.CharField(max_length=255)),
                ('outbound', models.BooleanField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.booking')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
