# Generated by Django 5.2.8 on 2025-11-22 09:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0006_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_no', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('validity', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('scheduled_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='airline_app.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='airline_app.airport')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
    ]
