# Generated by Django 5.2.8 on 2025-11-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0007_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('On Time', 'On Time'), ('Delayed', 'Delayed'), ('Boarding', 'Boarding'), ('Departed', 'Departed'), ('Arrived', 'Arrived'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(db_column='route_no', on_delete=django.db.models.deletion.CASCADE, to='airline_app.route')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
