# Generated by Django 5.2.8 on 2025-11-22 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0008_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('flight', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='airline_app.flight')),
                ('ticket', models.ForeignKey(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, to='airline_app.ticket')),
            ],
            options={
                'db_table': 'segments',
                'unique_together': {('ticket', 'flight')},
            },
        ),
    ]
