# Generated by Django 5.2.8 on 2025-11-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0009_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.IntegerField(blank=True, null=True)),
                ('boarding_time', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='airline_app.flight')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.seat')),
                ('ticket', models.ForeignKey(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, to='airline_app.ticket')),
            ],
            options={
                'db_table': 'boarding_passes',
                'unique_together': {('ticket', 'flight')},
            },
        ),
    ]
