# Generated by Django 5.2.8 on 2025-11-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0010_boardingpass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardingpass',
            options={'verbose_name_plural': 'Boarding Passes'},
        ),
    ]
