# Generated by Django 5.2.8 on 2025-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0011_alter_boardingpass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Запланирован'), ('On Time', 'По расписанию'), ('Delayed', 'Задерживается'), ('Boarding', 'Посадка'), ('Departed', 'Вылетел'), ('Arrived', 'Прибыл'), ('Cancelled', 'Отменен')], max_length=20),
        ),
    ]
