# Generated by Django 5.2.8 on 2025-12-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0014_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Payment'},
        ),
    ]
